name: commands workflow

on:
  workflow_dispatch: # 👈 Workflow runs only when triggered manually.

jobs:
  example:
    runs-on: ubuntu-latest # 👈 Runs on a Linux GitHub-hosted runner.
    steps:
      - name: check if a file exists
        run: |
          if [ -f "config.yaml" ]; then
            echo "::debug::config.yaml"
          else
            echo "::error::config.yaml is missing"
          fi
