name: manual workflow

on:
  workflow_dispatch:
    inputs: 
      environment:
        description: "choose environemnt"
        required: true
        default: "staging"
        type: choice
        options:
          - staging
          - production 

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy application
        run: echo "deploying the application to ${{ inputs.environment }}"
        
  
