name: scheduled workflow

on: 
  schedule:
    - cron: "*/5 * * * *"   # every 5 minutes

jobs:
  scheduled-task:
    runs-on: ubuntu-latest
    steps:
      - name: Print message
        run: echo "running the scheduled task at $(date -u)"
